const compgraph: string = `{
    "rootId":"root",
    "fragments":{
       "root":{
          "type":"DagLayout",
          "contents":{
             "nodes":{
                "0":{
                   "children":[
 
                   ],
                   "fragmentId":"aZTico6sbQ"
                },
                "1":{
                   "children":[
 
                   ],
                   "fragmentId":"53V9+epctP"
                },
                "2":{
                   "children":[
 
                   ],
                   "fragmentId":"7YYEtYqGae"
                },
                "3":{
                   "children":[
 
                   ],
                   "fragmentId":"k4/98KzMW0"
                },
                "4":{
                   "children":[
 
                   ],
                   "fragmentId":"zk1ZC7quyN"
                },
                "5":{
                   "children":[
 
                   ],
                   "fragmentId":"oGD7tWu3y/"
                },
                "6":{
                   "children":[
 
                   ],
                   "fragmentId":"nXRP9TJT1i"
                },
                "7":{
                   "children":[
 
                   ],
                   "fragmentId":"l3GDdVUdvs"
                },
                "8":{
                   "children":[
 
                   ],
                   "fragmentId":"qQcPdXzZnc"
                },
                "9":{
                   "children":[
 
                   ],
                   "fragmentId":"75LRSUCPQ/"
                },
                "10":{
                   "children":[
                      "3",
                      "4",
                      "5",
                      "6",
                      "7",
                      "8",
                      "9"
                   ],
                   "fragmentId":"2QBl9x8VD0"
                },
                "11":{
                   "children":[
 
                   ],
                   "fragmentId":"1/UznmQGiG"
                },
                "12":{
                   "children":[
 
                   ],
                   "fragmentId":"BmcmXyO+ie"
                },
                "13":{
                   "children":[
 
                   ],
                   "fragmentId":"H7DlKXD74V"
                },
                "14":{
                   "children":[
 
                   ],
                   "fragmentId":"FEciab03El"
                },
                "15":{
                   "children":[
 
                   ],
                   "fragmentId":"9tUNR6OCbG"
                },
                "16":{
                   "children":[
 
                   ],
                   "fragmentId":"jtVAXnvInc"
                },
                "17":{
                   "children":[
 
                   ],
                   "fragmentId":"UF1a0RiGBO"
                },
                "18":{
                   "children":[
                      "11",
                      "12",
                      "13",
                      "14",
                      "15",
                      "16",
                      "17"
                   ],
                   "fragmentId":"+EkFAxceI0"
                },
                "19":{
                   "children":[
 
                   ],
                   "fragmentId":"znxurnHgX2"
                },
                "20":{
                   "children":[
 
                   ],
                   "fragmentId":"GHhwPw7OJs"
                },
                "21":{
                   "children":[
 
                   ],
                   "fragmentId":"t1/XhlPs45"
                },
                "22":{
                   "children":[
 
                   ],
                   "fragmentId":"aCkt8U9rU9"
                },
                "23":{
                   "children":[
 
                   ],
                   "fragmentId":"PYScXXjEl0"
                },
                "24":{
                   "children":[
 
                   ],
                   "fragmentId":"L//WgHUSHR"
                },
                "25":{
                   "children":[
 
                   ],
                   "fragmentId":"LIzaDlXOH2"
                },
                "26":{
                   "children":[
                      "19",
                      "20",
                      "21",
                      "22",
                      "23",
                      "24",
                      "25"
                   ],
                   "fragmentId":"lJiCCE2p/p"
                },
                "27":{
                   "children":[
 
                   ],
                   "fragmentId":"y1ZLi9/Alr"
                },
                "28":{
                   "children":[
 
                   ],
                   "fragmentId":"aW8x282ehh"
                },
                "29":{
                   "children":[
 
                   ],
                   "fragmentId":"GgPinbb55b"
                },
                "30":{
                   "children":[
 
                   ],
                   "fragmentId":"5gk9T5BUQb"
                },
                "31":{
                   "children":[
 
                   ],
                   "fragmentId":"dNG0Qt3hg1"
                },
                "32":{
                   "children":[
 
                   ],
                   "fragmentId":"B+qRVauTvT"
                },
                "33":{
                   "children":[
 
                   ],
                   "fragmentId":"VLStiBDJ+5"
                },
                "34":{
                   "children":[
 
                   ],
                   "fragmentId":"TtMVcdEel2"
                },
                "35":{
                   "children":[
                      "28",
                      "29",
                      "30",
                      "31",
                      "32",
                      "33",
                      "34"
                   ],
                   "fragmentId":"6TMhJrqYRo"
                },
                "36":{
                   "children":[
 
                   ],
                   "fragmentId":"7DDVsuxoSG"
                },
                "37":{
                   "children":[
 
                   ],
                   "fragmentId":"nqVxcUCR5x"
                },
                "38":{
                   "children":[
 
                   ],
                   "fragmentId":"b6vJVYZCMK"
                },
                "39":{
                   "children":[
 
                   ],
                   "fragmentId":"HxzQNW6NI7"
                },
                "40":{
                   "children":[
 
                   ],
                   "fragmentId":"s7s5mropJf"
                },
                "41":{
                   "children":[
 
                   ],
                   "fragmentId":"YneDip3f4B"
                },
                "42":{
                   "children":[
 
                   ],
                   "fragmentId":"YtPyPyaEx+"
                },
                "43":{
                   "children":[
                      "36",
                      "37",
                      "38",
                      "39",
                      "40",
                      "41",
                      "42"
                   ],
                   "fragmentId":"qUAAx4q/hM"
                },
                "44":{
                   "children":[
 
                   ],
                   "fragmentId":"XZKsBlbIzV"
                },
                "45":{
                   "children":[
 
                   ],
                   "fragmentId":"rUpLyVjwd9"
                },
                "46":{
                   "children":[
 
                   ],
                   "fragmentId":"KyqCCcazFt"
                },
                "47":{
                   "children":[
 
                   ],
                   "fragmentId":"jKP+XDualV"
                },
                "48":{
                   "children":[
 
                   ],
                   "fragmentId":"lV1g9RPZWn"
                },
                "49":{
                   "children":[
 
                   ],
                   "fragmentId":"QB2KNJJvYK"
                },
                "50":{
                   "children":[
 
                   ],
                   "fragmentId":"LJN2h0RcwY"
                },
                "51":{
                   "children":[
                      "44",
                      "45",
                      "46",
                      "47",
                      "48",
                      "49",
                      "50"
                   ],
                   "fragmentId":"xldockeUqf"
                },
                "52":{
                   "children":[
 
                   ],
                   "fragmentId":"0H3jBsgFtp"
                },
                "53":{
                   "children":[
 
                   ],
                   "fragmentId":"6QPHWAz1Jf"
                },
                "54":{
                   "children":[
 
                   ],
                   "fragmentId":"Z5apXvwHcg"
                },
                "55":{
                   "children":[
 
                   ],
                   "fragmentId":"TX2Ic6lDB+"
                },
                "56":{
                   "children":[
 
                   ],
                   "fragmentId":"76B2Mf0+6r"
                },
                "57":{
                   "children":[
 
                   ],
                   "fragmentId":"yp0cJmg0fE"
                },
                "58":{
                   "children":[
 
                   ],
                   "fragmentId":"HGzr7G7LOb"
                },
                "59":{
                   "children":[
                      "52",
                      "53",
                      "54",
                      "55",
                      "56",
                      "57",
                      "58"
                   ],
                   "fragmentId":"srMUPxXcNd"
                },
                "60":{
                   "children":[
 
                   ],
                   "fragmentId":"7D+G2kWB69"
                },
                "61":{
                   "children":[
 
                   ],
                   "fragmentId":"DmzAnFpnQx"
                },
                "62":{
                   "children":[
 
                   ],
                   "fragmentId":"oiZIRIXv8a"
                },
                "63":{
                   "children":[
 
                   ],
                   "fragmentId":"ywu6NRnzNO"
                },
                "64":{
                   "children":[
 
                   ],
                   "fragmentId":"ZZtPOM4rpq"
                },
                "65":{
                   "children":[
 
                   ],
                   "fragmentId":"C6Q5qHeZ3z"
                },
                "66":{
                   "children":[
 
                   ],
                   "fragmentId":"r+vcRC8vLq"
                },
                "67":{
                   "children":[
 
                   ],
                   "fragmentId":"y6AjiFrJXb"
                },
                "68":{
                   "children":[
                      "61",
                      "62",
                      "63",
                      "64",
                      "65",
                      "66",
                      "67"
                   ],
                   "fragmentId":"miAszJDoWU"
                },
                "69":{
                   "children":[
                      "0",
                      "1",
                      "2",
                      "10",
                      "18",
                      "26",
                      "27",
                      "35",
                      "43",
                      "51",
                      "59",
                      "60",
                      "68"
                   ],
                   "fragmentId":"QT9CqriEJz"
                },
                "70":{
                   "children":[
 
                   ],
                   "fragmentId":"l4xqx/fIjL"
                },
                "71":{
                   "children":[
 
                   ],
                   "fragmentId":"Ch2w7LCBEz"
                },
                "72":{
                   "children":[
 
                   ],
                   "fragmentId":"YyXOHC2faQ"
                },
                "73":{
                   "children":[
 
                   ],
                   "fragmentId":"KeLKuHkdfW"
                },
                "74":{
                   "children":[
                      "70",
                      "71",
                      "72",
                      "73"
                   ],
                   "fragmentId":"etNLH3JMg3"
                },
                "75":{
                   "children":[
                      "69",
                      "74"
                   ],
                   "fragmentId":"dG9sGXcbvY"
                }
             },
             "edges":{
                "e0":{
                   "source":{
                      "id":"0"
                   },
                   "target":{
                      "id":"1"
                   }
                },
                "e1":{
                   "source":{
                      "id":"1"
                   },
                   "target":{
                      "id":"2"
                   }
                },
                "e2":{
                   "source":{
                      "id":"2"
                   },
                   "target":{
                      "id":"3"
                   }
                },
                "e3":{
                   "source":{
                      "id":"3"
                   },
                   "target":{
                      "id":"4"
                   }
                },
                "e4":{
                   "source":{
                      "id":"4"
                   },
                   "target":{
                      "id":"5"
                   }
                },
                "e5":{
                   "source":{
                      "id":"5"
                   },
                   "target":{
                      "id":"6"
                   }
                },
                "e6":{
                   "source":{
                      "id":"4"
                   },
                   "target":{
                      "id":"7"
                   }
                },
                "e7":{
                   "source":{
                      "id":"7"
                   },
                   "target":{
                      "id":"8"
                   }
                },
                "e8":{
                   "source":{
                      "id":"6"
                   },
                   "target":{
                      "id":"9"
                   }
                },
                "e9":{
                   "source":{
                      "id":"8"
                   },
                   "target":{
                      "id":"9"
                   }
                },
                "e10":{
                   "source":{
                      "id":"9"
                   },
                   "target":{
                      "id":"11"
                   }
                },
                "e11":{
                   "source":{
                      "id":"11"
                   },
                   "target":{
                      "id":"12"
                   }
                },
                "e12":{
                   "source":{
                      "id":"12"
                   },
                   "target":{
                      "id":"13"
                   }
                },
                "e13":{
                   "source":{
                      "id":"13"
                   },
                   "target":{
                      "id":"14"
                   }
                },
                "e14":{
                   "source":{
                      "id":"12"
                   },
                   "target":{
                      "id":"15"
                   }
                },
                "e15":{
                   "source":{
                      "id":"15"
                   },
                   "target":{
                      "id":"16"
                   }
                },
                "e16":{
                   "source":{
                      "id":"14"
                   },
                   "target":{
                      "id":"17"
                   }
                },
                "e17":{
                   "source":{
                      "id":"16"
                   },
                   "target":{
                      "id":"17"
                   }
                },
                "e18":{
                   "source":{
                      "id":"17"
                   },
                   "target":{
                      "id":"19"
                   }
                },
                "e19":{
                   "source":{
                      "id":"19"
                   },
                   "target":{
                      "id":"20"
                   }
                },
                "e20":{
                   "source":{
                      "id":"20"
                   },
                   "target":{
                      "id":"21"
                   }
                },
                "e21":{
                   "source":{
                      "id":"21"
                   },
                   "target":{
                      "id":"22"
                   }
                },
                "e22":{
                   "source":{
                      "id":"20"
                   },
                   "target":{
                      "id":"23"
                   }
                },
                "e23":{
                   "source":{
                      "id":"23"
                   },
                   "target":{
                      "id":"24"
                   }
                },
                "e24":{
                   "source":{
                      "id":"22"
                   },
                   "target":{
                      "id":"25"
                   }
                },
                "e25":{
                   "source":{
                      "id":"24"
                   },
                   "target":{
                      "id":"25"
                   }
                },
                "e26":{
                   "source":{
                      "id":"25"
                   },
                   "target":{
                      "id":"27"
                   }
                },
                "e27":{
                   "source":{
                      "id":"27"
                   },
                   "target":{
                      "id":"28"
                   }
                },
                "e28":{
                   "source":{
                      "id":"28"
                   },
                   "target":{
                      "id":"29"
                   }
                },
                "e29":{
                   "source":{
                      "id":"29"
                   },
                   "target":{
                      "id":"30"
                   }
                },
                "e30":{
                   "source":{
                      "id":"30"
                   },
                   "target":{
                      "id":"31"
                   }
                },
                "e31":{
                   "source":{
                      "id":"29"
                   },
                   "target":{
                      "id":"32"
                   }
                },
                "e32":{
                   "source":{
                      "id":"32"
                   },
                   "target":{
                      "id":"33"
                   }
                },
                "e33":{
                   "source":{
                      "id":"31"
                   },
                   "target":{
                      "id":"34"
                   }
                },
                "e34":{
                   "source":{
                      "id":"33"
                   },
                   "target":{
                      "id":"34"
                   }
                },
                "e35":{
                   "source":{
                      "id":"34"
                   },
                   "target":{
                      "id":"36"
                   }
                },
                "e36":{
                   "source":{
                      "id":"36"
                   },
                   "target":{
                      "id":"37"
                   }
                },
                "e37":{
                   "source":{
                      "id":"37"
                   },
                   "target":{
                      "id":"38"
                   }
                },
                "e38":{
                   "source":{
                      "id":"38"
                   },
                   "target":{
                      "id":"39"
                   }
                },
                "e39":{
                   "source":{
                      "id":"37"
                   },
                   "target":{
                      "id":"40"
                   }
                },
                "e40":{
                   "source":{
                      "id":"40"
                   },
                   "target":{
                      "id":"41"
                   }
                },
                "e41":{
                   "source":{
                      "id":"39"
                   },
                   "target":{
                      "id":"42"
                   }
                },
                "e42":{
                   "source":{
                      "id":"41"
                   },
                   "target":{
                      "id":"42"
                   }
                },
                "e43":{
                   "source":{
                      "id":"42"
                   },
                   "target":{
                      "id":"44"
                   }
                },
                "e44":{
                   "source":{
                      "id":"44"
                   },
                   "target":{
                      "id":"45"
                   }
                },
                "e45":{
                   "source":{
                      "id":"45"
                   },
                   "target":{
                      "id":"46"
                   }
                },
                "e46":{
                   "source":{
                      "id":"46"
                   },
                   "target":{
                      "id":"47"
                   }
                },
                "e47":{
                   "source":{
                      "id":"45"
                   },
                   "target":{
                      "id":"48"
                   }
                },
                "e48":{
                   "source":{
                      "id":"48"
                   },
                   "target":{
                      "id":"49"
                   }
                },
                "e49":{
                   "source":{
                      "id":"47"
                   },
                   "target":{
                      "id":"50"
                   }
                },
                "e50":{
                   "source":{
                      "id":"49"
                   },
                   "target":{
                      "id":"50"
                   }
                },
                "e51":{
                   "source":{
                      "id":"50"
                   },
                   "target":{
                      "id":"52"
                   }
                },
                "e52":{
                   "source":{
                      "id":"52"
                   },
                   "target":{
                      "id":"53"
                   }
                },
                "e53":{
                   "source":{
                      "id":"53"
                   },
                   "target":{
                      "id":"54"
                   }
                },
                "e54":{
                   "source":{
                      "id":"54"
                   },
                   "target":{
                      "id":"55"
                   }
                },
                "e55":{
                   "source":{
                      "id":"53"
                   },
                   "target":{
                      "id":"56"
                   }
                },
                "e56":{
                   "source":{
                      "id":"56"
                   },
                   "target":{
                      "id":"57"
                   }
                },
                "e57":{
                   "source":{
                      "id":"55"
                   },
                   "target":{
                      "id":"58"
                   }
                },
                "e58":{
                   "source":{
                      "id":"57"
                   },
                   "target":{
                      "id":"58"
                   }
                },
                "e59":{
                   "source":{
                      "id":"58"
                   },
                   "target":{
                      "id":"60"
                   }
                },
                "e60":{
                   "source":{
                      "id":"60"
                   },
                   "target":{
                      "id":"61"
                   }
                },
                "e61":{
                   "source":{
                      "id":"61"
                   },
                   "target":{
                      "id":"62"
                   }
                },
                "e62":{
                   "source":{
                      "id":"62"
                   },
                   "target":{
                      "id":"63"
                   }
                },
                "e63":{
                   "source":{
                      "id":"63"
                   },
                   "target":{
                      "id":"64"
                   }
                },
                "e64":{
                   "source":{
                      "id":"62"
                   },
                   "target":{
                      "id":"65"
                   }
                },
                "e65":{
                   "source":{
                      "id":"65"
                   },
                   "target":{
                      "id":"66"
                   }
                },
                "e66":{
                   "source":{
                      "id":"64"
                   },
                   "target":{
                      "id":"67"
                   }
                },
                "e67":{
                   "source":{
                      "id":"66"
                   },
                   "target":{
                      "id":"67"
                   }
                },
                "e68":{
                   "source":{
                      "id":"67"
                   },
                   "target":{
                      "id":"70"
                   }
                },
                "e69":{
                   "source":{
                      "id":"70"
                   },
                   "target":{
                      "id":"71"
                   }
                },
                "e70":{
                   "source":{
                      "id":"71"
                   },
                   "target":{
                      "id":"72"
                   }
                },
                "e71":{
                   "source":{
                      "id":"72"
                   },
                   "target":{
                      "id":"73"
                   }
                }
             },
             "alignments":[
 
             ]
          },
          "meta":{
 
          }
       },
       "aZTico6sbQ":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "53V9+epctP":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "7YYEtYqGae":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"MaxPool2d",
             "color":"blue"
          },
          "meta":{
 
          }
       },
       "k4/98KzMW0":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "zk1ZC7quyN":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "oGD7tWu3y/":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "nXRP9TJT1i":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "l3GDdVUdvs":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "qQcPdXzZnc":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "75LRSUCPQ/":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"torch.cat",
             "color":"yellow"
          },
          "meta":{
 
          }
       },
       "2QBl9x8VD0":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Fire",
             "color":"orange"
          },
          "meta":{
 
          }
       },
       "1/UznmQGiG":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "BmcmXyO+ie":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "H7DlKXD74V":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "FEciab03El":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "9tUNR6OCbG":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "jtVAXnvInc":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "UF1a0RiGBO":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"torch.cat",
             "color":"yellow"
          },
          "meta":{
 
          }
       },
       "+EkFAxceI0":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Fire",
             "color":"orange"
          },
          "meta":{
 
          }
       },
       "znxurnHgX2":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "GHhwPw7OJs":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "t1/XhlPs45":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "aCkt8U9rU9":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "PYScXXjEl0":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "L//WgHUSHR":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "LIzaDlXOH2":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"torch.cat",
             "color":"yellow"
          },
          "meta":{
 
          }
       },
       "lJiCCE2p/p":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Fire",
             "color":"orange"
          },
          "meta":{
 
          }
       },
       "y1ZLi9/Alr":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"MaxPool2d",
             "color":"blue"
          },
          "meta":{
 
          }
       },
       "aW8x282ehh":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "GgPinbb55b":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "5gk9T5BUQb":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "dNG0Qt3hg1":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "B+qRVauTvT":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "VLStiBDJ+5":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "TtMVcdEel2":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"torch.cat",
             "color":"yellow"
          },
          "meta":{
 
          }
       },
       "6TMhJrqYRo":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Fire",
             "color":"orange"
          },
          "meta":{
 
          }
       },
       "7DDVsuxoSG":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "nqVxcUCR5x":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "b6vJVYZCMK":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "HxzQNW6NI7":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "s7s5mropJf":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "YneDip3f4B":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "YtPyPyaEx+":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"torch.cat",
             "color":"yellow"
          },
          "meta":{
 
          }
       },
       "qUAAx4q/hM":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Fire",
             "color":"orange"
          },
          "meta":{
 
          }
       },
       "XZKsBlbIzV":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "rUpLyVjwd9":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "KyqCCcazFt":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "jKP+XDualV":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "lV1g9RPZWn":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "QB2KNJJvYK":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "LJN2h0RcwY":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"torch.cat",
             "color":"yellow"
          },
          "meta":{
 
          }
       },
       "xldockeUqf":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Fire",
             "color":"orange"
          },
          "meta":{
 
          }
       },
       "0H3jBsgFtp":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "6QPHWAz1Jf":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "Z5apXvwHcg":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "TX2Ic6lDB+":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "76B2Mf0+6r":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "yp0cJmg0fE":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "HGzr7G7LOb":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"torch.cat",
             "color":"yellow"
          },
          "meta":{
 
          }
       },
       "srMUPxXcNd":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Fire",
             "color":"orange"
          },
          "meta":{
 
          }
       },
       "7D+G2kWB69":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"MaxPool2d",
             "color":"blue"
          },
          "meta":{
 
          }
       },
       "DmzAnFpnQx":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "oiZIRIXv8a":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "ywu6NRnzNO":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "ZZtPOM4rpq":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "C6Q5qHeZ3z":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "r+vcRC8vLq":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "y6AjiFrJXb":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"torch.cat",
             "color":"yellow"
          },
          "meta":{
 
          }
       },
       "miAszJDoWU":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Fire",
             "color":"orange"
          },
          "meta":{
 
          }
       },
       "QT9CqriEJz":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Sequential",
             "color":"red"
          },
          "meta":{
 
          }
       },
       "l4xqx/fIjL":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Dropout",
             "color":"pink"
          },
          "meta":{
 
          }
       },
       "Ch2w7LCBEz":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Conv2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "YyXOHC2faQ":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"ReLU",
             "color":"purple"
          },
          "meta":{
 
          }
       },
       "KeLKuHkdfW":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"AdaptiveAvgPool2d",
             "color":"green"
          },
          "meta":{
 
          }
       },
       "etNLH3JMg3":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"Sequential",
             "color":"red"
          },
          "meta":{
 
          }
       },
       "dG9sGXcbvY":{
          "type":"TokenPrimitive",
          "contents":{
             "text":"SqueezeNet",
             "color":"purple"
          },
          "meta":{
 
          }
       }
    }
 }`;
 export default compgraph;